import { Component } from '@angular/core';
import { NgFor, NgOptimizedImage } from "@angular/common";

@Component({
  standalone: true,
  selector: 'app-image-gallery',
  imports: [NgFor, NgOptimizedImage],
  templateUrl: './image-gallery.component.html',
  styleUrls: ['./image-gallery.component.scss']
})
export class ImageGalleryComponent {
  images = [
    {url: 'assets/images/kt-1.jpg', title: "Olivia"},
    {url: 'assets/images/kt-2.jpg', title: "Neodesha"},
    {url: 'assets/images/kt-3.jpg', title: "Olivia at the beach"},
    {url: 'assets/images/kt-4.jpg', title: "Spooky moon"},
    {url: 'assets/images/kt-5.jpg', title: "Full moon"},
    {url: 'assets/images/kt-6.jpg', title: "Portofino boat"},
    {url: 'assets/images/kt-7.jpg', title: "Mountains"},
    {url: 'assets/images/kt-8.jpg', title: "Sandy and Barb"},
    {url: 'assets/images/kt-9.jpg', title: "Mountains behind lake"},
    {url: 'assets/images/kt-10.jpg', title: "Steamboat ferry"},
    {url: 'assets/images/kt-11.jpg', title: "Remote island"},
    {url: 'assets/images/kt-12.jpg', title: "Flowing river"},
    {url: 'assets/images/kt-13.jpg', title: "Remote island fishermen"},
    {url: 'assets/images/kt-14.jpg', title: "Sandy and Barb at lunch"},
    {url: 'assets/images/kt-15.jpg', title: "Airstream camping spot"},
    {url: 'assets/images/kt-16.jpg', title: "Sunset mountains"},
    {url: 'assets/images/kt-17.jpg', title: "Sunset mountains 2"},
    {url: 'assets/images/kt-18.jpg', title: "Sunset mountains 3"},
    {url: 'assets/images/kt-19.jpg', title: "Sunset mountains 4"},
    {url: 'assets/images/kt-20.jpg', title: "Campsite and grill"},
    // {url: 'assets/images/kt-21.jpg', title: "Low flood stage water"},
    // {url: 'assets/images/kt-22.jpg', title: "Olivia in the shade"},
    // {url: 'assets/images/kt-23.jpg', title: "Sunset at the arid lake"},
    // {url: 'assets/images/kt-24.jpg', title: "Picnic area at sunset"},
    // {url: 'assets/images/kt-25.jpg', title: "Mountains through the bushes"},
    // {url: 'assets/images/kt-26.jpg', title: "Lake dock"},
    // {url: 'assets/images/kt-27.jpg', title: "Lake dock 2"},
    // {url: 'assets/images/kt-28.jpg', title: "Lake dock 3"},
    // {url: 'assets/images/kt-29.jpg', title: "Wide angle lake and mountains"},
    // {url: 'assets/images/kt-30.jpg', title: "Snowcap mountains and lake"},
    // {url: 'assets/images/kt-31.jpg', title: "Boulder island"},
    // {url: 'assets/images/kt-32.jpg', title: "Hollow redwook tree trunk"},
    // {url: 'assets/images/kt-33.jpg', title: "Ancient redwood tree"},
    // {url: 'assets/images/kt-34.jpg', title: "Redwoods and undergrowth"},
    // {url: 'assets/images/kt-35.jpg', title: "Sandy's custom binoculars"},
    // {url: 'assets/images/kt-36.jpg', title: "Vertical redwood trees"},
    // {url: 'assets/images/kt-37.jpg', title: "Inside the hollow redwood tree trunk"},
    // {url: 'assets/images/kt-38.jpg', title: "Sandy inside the hollow redwood tree trunk"},
    // {url: 'assets/images/kt-39.jpg', title: "Sandy in the fallen petrified tree trunks"},
    // {url: 'assets/images/kt-40.jpg', title: "Inside the fallen petrified tree trunks"},
    // {url: 'assets/images/kt-41.jpg', title: "The roots of the fallen petrified tree"},
    // {url: 'assets/images/kt-42.jpg', title: "A redwood tree estimated to be hundreds of years old"},
    // {url: 'assets/images/kt-43.jpg', title: "Sunset in the redwood forest"},
    // {url: 'assets/images/kt-44.jpg', title: "Lakeside cabin in the forest"},
    // {url: 'assets/images/kt-45.jpg', title: "Olivia and the pine cone collection"},
    // {url: 'assets/images/kt-46.jpg', title: "Blooming flowers"},
    // {url: 'assets/images/kt-47.jpg', title: "A duck on a fallen tree in the water"},
    // {url: 'assets/images/kt-48.jpg', title: "Scenic mountains in the distance while ayaking on the river"},
    // {url: 'assets/images/kt-49.jpg', title: "Mountain streams"},
    // {url: 'assets/images/kt-50.jpg', title: "The airstream campground in the distance"},
    // {url: 'assets/images/kt-51.jpg', title: "Sandy and Olivia at Hume Lake trail, Sequioia National Forest"},
    // {url: 'assets/images/kt-52.jpg', title: "Sandy smelling flowers on Hume Lake trail"},
    // {url: 'assets/images/kt-53.jpg', title: "Natural rock formations and boulders on Hume Lake trail"},
    // {url: 'assets/images/kt-54.jpg', title: "Olivia in the shade of the airstream camp in the Sequioia National Forest"},
    // {url: 'assets/images/kt-55.jpg', title: "Distant trees and rolling hills"},
    // {url: 'assets/images/kt-56.jpg', title: "Historic Moore Cottage"},
    // {url: 'assets/images/kt-57.jpg', title: "Historic Wawona Hotel"},
    // {url: 'assets/images/kt-58.jpg', title: "Huge, old Sequioia tree"},
    // {url: 'assets/images/kt-59.jpg', title: "Sequioia tree trunks"},
    // {url: 'assets/images/kt-60.jpg', title: "Sequioia tree with path through it's trunk"},
    // {url: 'assets/images/kt-61.jpg', title: "Fallen Sequioia roots"},
    // {url: 'assets/images/kt-62.jpg', title: "Female doe feeding in the forest"},
    // {url: 'assets/images/kt-63.jpg', title: "Airstream camp setup"},
    // {url: 'assets/images/kt-64.jpg', title: "Natural rock formations in the campground"},
    // {url: 'assets/images/kt-65.jpg', title: "Wood fire at the campsite while Olivia rests on her blanket"},
    // {url: 'assets/images/kt-66.jpg', title: "Rushing rapids from heavy rain"},
    // {url: 'assets/images/kt-68.jpg', title: "Rushing rapids from heavy rain"},
    // {url: 'assets/images/kt-69.jpg', title: "Mountain face in the background"},
    // {url: 'assets/images/kt-71.jpg', title: "Rushing waterfall view through the trees"},
    // {url: 'assets/images/kt-72.jpg', title: "Rushing waterfall view from below"},
    // {url: 'assets/images/kt-73.jpg', title: "Natural river created by waterfall runoff"},
    // {url: 'assets/images/kt-74.jpg', title: "Mountain face below clouds"},
    // {url: 'assets/images/kt-75.jpg', title: "Rushing rapids from the waterfall up close"},
    // {url: 'assets/images/kt-76.jpg', title: "Rushing rapids from the waterfall"},
    // {url: 'assets/images/kt-78.jpg', title: "Waterfall framed by Redwood trees"},
    // {url: 'assets/images/kt-79.jpg', title: "Waterfall framed by Redwood trees 2"},
    // {url: 'assets/images/kt-80.jpg', title: "River rapids with mountain forest behind"},
    // {url: 'assets/images/kt-81.jpg', title: "Sandy rests at the airstream camp"},
    // {url: 'assets/images/kt-82.jpg', title: "Vast plains, lake and far off mountains"},
    // {url: 'assets/images/kt-83.jpg', title: "Airstream next to an old garage"},
    // {url: 'assets/images/kt-84.jpg', title: "Black dog on the sidewalk near the airstream"},
    // {url: 'assets/images/kt-85.jpg', title: "Snowcap mountains behind a lake with a fishing boat"},
    // {url: 'assets/images/kt-86.jpg', title: "Snowcap mountains behind a lake bend"}
  ]
  
  shuffleImages = () => {
    let randomizedImages = this.images.sort((a,b) => 0.5 - Math.random())
    console.log(randomizedImages);
  }

  
}
