import { Component, OnInit } from '@angular/core';
import { NgFor, NgOptimizedImage } from "@angular/common";

@Component({
  standalone: true,
  selector: 'app-image-gallery',
  imports: [NgFor, NgOptimizedImage],
  templateUrl: './image-gallery.component.html',
  styleUrls: ['./image-gallery.component.scss']
})
export class ImageGalleryComponent implements OnInit {
  images = [
    {url: 'assets/images/01.jpg', title: "Olivia"},
    {url: 'assets/images/02.jpg', title: "Neodesha"},
    {url: 'assets/images/03.jpg', title: "Olivia at the beach"},
    {url: 'assets/images/04.jpg', title: "Spooky moon"},
    {url: 'assets/images/05.jpg', title: "Full moon"},
    {url: 'assets/images/06.jpg', title: "Portofino boat"},
    {url: 'assets/images/07.jpg', title: "Mountains"},
    {url: 'assets/images/08.jpg', title: "Sandy and Barb"},
    {url: 'assets/images/09.jpg', title: "Mountains behind lake"},
    {url: 'assets/images/010.jpg', title: "Steamboat ferry"},
    {url: 'assets/images/011.jpg', title: "Remote island"},
    {url: 'assets/images/012.jpg', title: "Flowing river"},
    {url: 'assets/images/013.jpg', title: "Remote island fishermen"},
    {url: 'assets/images/014.jpg', title: "Sandy and Barb at lunch"},
    {url: 'assets/images/015.jpg', title: "Airstream camping spot"},
    {url: 'assets/images/016.jpg', title: "Sunset mountains"},
    {url: 'assets/images/017.jpg', title: "Sunset mountains 2"},
    {url: 'assets/images/018.jpg', title: "Sunset mountains 3"},
    {url: 'assets/images/019.jpg', title: "Sunset mountains 4"},
    {url: 'assets/images/020.jpg', title: "Campsite and grill"},
    {url: 'assets/images/021.jpg', title: "Low flood stage water"},
    {url: 'assets/images/022.jpg', title: "Olivia in the shade"},
    {url: 'assets/images/023.jpg', title: "Sunset at the arid lake"},
    {url: 'assets/images/024.jpg', title: "Picnic area at sunset"},
    {url: 'assets/images/025.jpg', title: "Mountains through the bushes"},
    {url: 'assets/images/026.jpg', title: "Lake dock"},
    {url: 'assets/images/027.jpg', title: "Lake dock 2"},
    {url: 'assets/images/028.jpg', title: "Lake dock 3"},
    {url: 'assets/images/029.jpg', title: "Wide angle lake and mountains"},
    {url: 'assets/images/030.jpg', title: "Snowcap mountains and lake"},
    {url: 'assets/images/031.jpg', title: "Boulder island"},
    {url: 'assets/images/032.jpg', title: "Hollow redwook tree trunk"},
    {url: 'assets/images/033.jpg', title: "Ancient redwood tree"},
    {url: 'assets/images/034.jpg', title: "Redwoods and undergrowth"},
    {url: 'assets/images/035.jpg', title: "Sandy's custom binoculars"},
    {url: 'assets/images/036.jpg', title: "Vertical redwood trees"},
    {url: 'assets/images/037.jpg', title: "Inside the hollow redwood tree trunk"},
    {url: 'assets/images/038.jpg', title: "Sandy inside the hollow redwood tree trunk"},
    {url: 'assets/images/039.jpg', title: "Sandy in the fallen petrified tree trunks"},
    {url: 'assets/images/040.jpg', title: "Inside the fallen petrified tree trunks"},
    {url: 'assets/images/041.jpg', title: "The roots of the fallen petrified tree"},
    {url: 'assets/images/042.jpg', title: "A redwood tree estimated to be hundreds of years old"},
    {url: 'assets/images/043.jpg', title: "Sunset in the redwood forest"},
    {url: 'assets/images/044.jpg', title: "Lakeside cabin in the forest"},
    {url: 'assets/images/045.jpg', title: "Olivia and the pine cone collection"},
    {url: 'assets/images/046.jpg', title: "Blooming flowers"},
    {url: 'assets/images/047.jpg', title: "A duck on a fallen tree in the water"},
    {url: 'assets/images/048.jpg', title: "Scenic mountains in the distance while ayaking on the river"},
    {url: 'assets/images/049.jpg', title: "Mountain streams"},
    {url: 'assets/images/050.jpg', title: "The airstream campground in the distance"},
    {url: 'assets/images/051.jpg', title: "Sandy and Olivia at Hume Lake trail, Sequioia National Forest"},
    {url: 'assets/images/052.jpg', title: "Sandy smelling flowers on Hume Lake trail"},
    {url: 'assets/images/053.jpg', title: "Natural rock formations and boulders on Hume Lake trail"},
    {url: 'assets/images/054.jpg', title: "Olivia in the shade of the airstream camp in the Sequioia National Forest"},
    {url: 'assets/images/055.jpg', title: "Distant trees and rolling hills"},
    {url: 'assets/images/056.jpg', title: "Historic Moore Cottage"},
    {url: 'assets/images/057.jpg', title: "Historic Wawona Hotel"},
    {url: 'assets/images/058.jpg', title: "Huge, old Sequioia tree"},
    {url: 'assets/images/059.jpg', title: "Sequioia tree trunks"},
    {url: 'assets/images/060.jpg', title: "Sequioia tree with path through it's trunk"},
    {url: 'assets/images/061.jpg', title: "Fallen Sequioia roots"},
    {url: 'assets/images/062.jpg', title: "Female doe feeding in the forest"},
    {url: 'assets/images/063.jpg', title: "Airstream camp setup"},
    {url: 'assets/images/064.jpg', title: "Natural rock formations in the campground"},
    {url: 'assets/images/065.jpg', title: "Wood fire at the campsite while Olivia rests on her blanket"},
    {url: 'assets/images/066.jpg', title: "Rushing rapids from heavy rain"},
    {url: 'assets/images/068.jpg', title: "Rushing rapids from heavy rain"},
    {url: 'assets/images/069.jpg', title: "Mountain face in the background"},
    {url: 'assets/images/071.jpg', title: "Rushing waterfall view through the trees"},
    {url: 'assets/images/072.jpg', title: "Rushing waterfall view from below"},
    {url: 'assets/images/073.jpg', title: "Natural river created by waterfall runoff"},
    {url: 'assets/images/074.jpg', title: "Mountain face below clouds"},
    {url: 'assets/images/075.jpg', title: "Rushing rapids from the waterfall up close"},
    {url: 'assets/images/076.jpg', title: "Rushing rapids from the waterfall"},
    {url: 'assets/images/078.jpg', title: "Waterfall framed by Redwood trees"},
    {url: 'assets/images/079.jpg', title: "Waterfall framed by Redwood trees 2"},
    {url: 'assets/images/080.jpg', title: "River rapids with mountain forest behind"},
    {url: 'assets/images/081.jpg', title: "Sandy rests at the airstream camp"},
    {url: 'assets/images/082.jpg', title: "Vast plains, lake and far off mountains"},
    {url: 'assets/images/083.jpg', title: "Airstream next to an old garage"},
    {url: 'assets/images/084.jpg', title: "Black dog on the sidewalk near the airstream"},
    {url: 'assets/images/085.jpg', title: "Snowcap mountains behind a lake with a fishing boat"},
    {url: 'assets/images/086.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/087.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/088.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/089.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/090.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/091.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/092.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/093.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/094.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/095.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/096.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/097.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/098.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/099.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0100.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0101.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0102.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0103.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0104.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0105.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0106.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0107.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0108.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0109.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0110.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0111.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0112.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0113.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0114.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0115.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0116.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0117.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0118.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0119.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0120.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0121.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0122.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0123.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0124.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0125.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0126.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0127.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0128.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0129.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0130.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0131.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0132.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0133.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0134.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0136.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0137.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0138.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0139.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0140.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0141.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0142.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0143.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0145.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0146.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0147.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0148.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0149.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0150.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0151.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0152.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0153.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0154.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0155.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0156.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0157.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0158.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0159.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0160.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0161.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0162.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0163.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0164.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0165.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0166.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0167.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0168.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0169.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0170.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0171.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0172.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0173.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0174.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0175.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0176.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0177.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0178.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0179.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0180.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0181.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0182.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0183.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0184.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0185.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0186.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0187.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0188.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0189.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0190.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0191.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0192.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0193.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0194.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0195.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0196.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0197.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0198.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0199.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0200.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0201.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0202.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0203.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0204.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0205.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0206.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0207.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0208.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0209.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0210.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0211.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0212.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0213.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0214.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0215.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0216.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0217.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0218.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0219.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0220.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0221.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0222.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0223.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0224.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0225.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0226.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0227.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0228.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0229.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0230.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0231.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0232.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0233.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0234.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0235.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0236.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0237.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0238.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0239.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0240.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0241.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0242.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0243.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0244.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0245.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0246.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0247.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0248.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0249.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0250.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0251.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0252.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0253.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0254.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0255.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0256.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0257.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0258.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0259.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0260.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0261.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0262.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0263.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0264.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0265.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0266.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0267.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0268.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0269.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0270.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0271.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0272.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0274.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0275.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0276.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0277.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0278.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0279.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0280.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0281.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0282.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0283.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0284.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0285.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0286.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0287.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0288.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0289.jpg', title: "Snowcap mountains behind a lake bend"},
    {url: 'assets/images/0290.jpg', title: "Snowcap mountains behind a lake bend"}
  ]

  tagUrl = 'https://res.cloudinary.com/de1d1dq0v/image/list/wandering.json';
  exampleUrl = 'https://res.cloudinary.com/de1d1dq0v/image/upload/v1688088193/053_i2limy.jpg';

  newImgArr: string[] = [];


  shuffleImages = () => {
    let randomizedImages = this.newImgArr.sort((a,b) => 0.5 - Math.random())
    //console.log(randomizedImages);
  }

  ngOnInit(): void {

    fetch(this.tagUrl)
      .then((res) => res.json())
      .then((data) => {
        data.resources.forEach((img: any) => {
          let {public_id, version, format} = img;
          let imgUrl = `https://res.cloudinary.com/de1d1dq0v/image/upload/f_auto/q_auto/v${version}/${public_id}.${format}`;
          this.newImgArr.push(imgUrl);        
        });
      })
      .catch((error) => console.error(error))
      .finally(() => this.shuffleImages());
  }

  
}
